### ISSUE TITLE
How do you disable tracing some requests in Rails?

### ISSUE THREAD

**Issue by iconara** [aws/aws-xray-sdk-ruby#17]
I'm adding the X-Ray SDK to a Rails application, and I'm struggling with understanding how to disable tracing for some requests. I've figured out that you can use the sampling feature for this, for some situations, however not for my case.

We have monitoring that hits the root route of the application, and this creates a lot of noise in X-Ray and we really would prefer to not have those traces at all. What I would need in order to use the sampling feature to disable tracing for these requests is an ability to look at the user agent, but that doesn't seem to be supported.

It seems like an easy fix, and I would be happy to submit a PR for that, but it also seems to me that sampling and disabling are different things. If I didn't use the X-Ray SDK's middleware, I would simply just not start a segment for the requests I didn't want to trace (this is in fact what we do in non-Rails applications where we don't use the X-Ray SDK).

Is sampling really the way to go to solve this, or is there another way I haven't figured out?

**Comment by haotianw465** [comment]
The SDK right now can only do sampling rule matching based on http method, path and host. We will take this as a feature request to add user agent as part of sampling rule configuration.

The only workaround is to pass your own sampler that implement the `sampler` interface https://github.com/aws/aws-xray-sdk-ruby/blob/master/lib/aws-xray-sdk/sampling/sampler.rb. That way you can pass custom rules that contains user agent, and the sampler do the matching based on user agent.

The other possible option is to have a separate path `/healthcheck` so you can use all the built-in functionality. This has been a go-to solution for a lot of users need to disable tracing on health check. Could you let me know if this is feasible for your use case?

**Comment by iconara** [comment]
Could you explain more how the workaround would work? It looks to me like the blocker is that the information given to the sampler is fixed (see https://github.com/aws/aws-xray-sdk-ruby/blob/24b478e3261ea4bb4cc3e042a4d7b66c50570217/lib/aws-xray-sdk/facets/rack.rb#L30-L32) and implementing my own sampler wouldn't change that, would it? I understand that I can pass any information I want to the custom sampler when it is created, but the user agent of a request won't be known at the time the sampler is created.

Having a separate path for these checks is not an option unfortunately – there are other monitoring requests that go to a specific path that's easily identifiable and I've already disabled tracing for those using the method you described, but there are monitoring requests where that is not applicable, unfortunately.

Would you be open to a PR that added the Rack env to the information passed to the sampler?

**Comment by haotianw465** [comment]
Yes. As long as it doesn't break the sampler functionality for non-Rack applications.
