### ISSUE TITLE
UDP Packet size limit

### ISSUE THREAD

**Issue by bigplants** [aws/aws-xray-sdk-ruby#28]
Hi,

I faced the bellow warning in Xray SDK log:
```
W, [2019-07-01T03:04:35.414605 #22440]  WARN -- : failed to send payload due to Message too long - send(2)
```

My segment entry is over `65507bytes` that is UDP payload size limit.

Do you have any solutions like splitting or cutting segment?

**Comment by ss2305** [comment]
@bigplants Apologies for the late response. Yes the UDP limit is 64 kb so you are hitting that threshold. One way to get around this is by reducing the default [https://github.com/aws/aws-xray-sdk-ruby/blob/135a9187a1f9b424c3179609906b2f4256eeda18/lib/aws-xray-sdk/streaming/default_streamer.rb#L13](url)threshold to below 50 and see if that works.

Meanwhile can you describe your use case? Are you trying to add additional payload to your segment ?
