### ISSUE TITLE
Regarding next release date

### ISSUE THREAD

**Issue by nerixim** [aws/aws-xray-sdk-ruby#33]
Hi guys, thanks for your work on X-Ray for Ruby.
As a serverless enthusiast I’m very excited with Lambda instrumentation made possible in a recent PR #20.

Do you have plans to release anytime soon?

**Comment by srprash** [comment]
Hi @nerixim , we will prioritize a release soon. Stay tuned!

**Comment by nerixim** [comment]
https://github.com/aws/aws-xray-sdk-ruby/releases/tag/0.11.3
Thanks @srprash !
