### ISSUE TITLE
has_header? missing on old rack version

### ISSUE THREAD

**Issue by masterkain** [aws/aws-xray-sdk-ruby#44]
```
gem 'aws-xray-sdk', require: ['aws-xray-sdk/facets/rails/railtie']
```

```
 #<NoMethodError: undefined method `has_header?' for #<Rack::Request:0x000056350963a080>>
 /bundle/vendor/gems/aws-xray-sdk-0.10.2/lib/aws-xray-sdk/facets/rack.rb:69:in `extract_request_meta'
 /bundle/vendor/gems/aws-xray-sdk-0.10.2/lib/aws-xray-sdk/facets/rack.rb:40:in `call'
 /bundle/vendor/gems/railties-4.2.11.1/lib/rails/engine.rb:518:in `call'
 /bundle/vendor/gems/railties-4.2.11.1/lib/rails/application.rb:165:in `call'
 /bundle/vendor/gems/rack-pjax-1.0.0/lib/rack/pjax.rb:12:in `call'
 /bundle/vendor/gems/puma-4.3.1/lib/puma/configuration.rb:228:in `call'
 /bundle/vendor/gems/puma-4.3.1/lib/puma/server.rb:681:in `handle_request'
 /bundle/vendor/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
 /bundle/vendor/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
 /bundle/vendor/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

```
rails 4.2.11.1
rack 1.6.12
```

fairly old version of rails/rack app, tried adding xray tracing anyway.
maybe we should check about `rack ~> 2.0` like in gemspec devdependencies or can this be adjusted for older rack versions?

**Comment by srprash** [comment]
Hi @masterkain 
I think the problem is with the rails version. Our [documentation](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-ruby.html) mentions that rails version 5.1 or later is required. 
Let me know if the issue persists even after upgrading the rails version.

**Comment by masterkain** [comment]
hello @srprash,
yeah I'm aware, what I mean is that first I tried installing the gem and after reading the whole docs: if the `bundle` process stopped me right away maybe it would have been best.

in order for this my suggestion was to adjust the rack version in gemspec

cheers
