### ISSUE TITLE
warning: instance variable @metadata not initialized

### ISSUE THREAD

**Issue by etiennechabert** [aws/aws-xray-sdk-ruby#84]
Hello, 

Version used: aws-xray-sdk-0.13.0

I am flooded by warnings such as:
```
/usr/local/bundle/gems/aws-xray-sdk-0.13.0/lib/aws-xray-sdk/model/entity.rb:158: warning: instance variable @metadata not initialized
```
Coming from this line: https://github.com/aws/aws-xray-sdk-ruby/blob/master/lib/aws-xray-sdk/model/entity.rb#L158

I have the feeling that this could be easily prevented if Instead of using directly, `@metadata`, we would be using the `metadata` method ? https://github.com/aws/aws-xray-sdk-ruby/blob/master/lib/aws-xray-sdk/model/entity.rb#L64

Sorry if I am totally missing something and this warning is actually because I am doing something wrong.

Best,

**Comment by willarmiros** [comment]
Hi @etiennechabert - I think you're correct, I'm not exactly a Ruby expert but if you're interested in making a simple PR for this change we would definitely approve.

**Comment by etiennechabert** [comment]
@willarmiros thanks for the opportunity to contribute, let's continue the discussion in the PR I just created

**Comment by etiennechabert** [comment]
Closing after merge of: https://github.com/aws/aws-xray-sdk-ruby/pull/86

**Comment by etiennechabert** [comment]
@willarmiros would you be so kind to push for a new release to be created? I would like to update my gem and see the warnings be gone.

Thanks in advance

**Comment by willarmiros** [comment]
Hi @etiennechabert we have a release planned, but unfortunately I cannot provide ETAs. Feel free to watch the repo to get notified at the next release.

**Comment by etiennechabert** [comment]
Thanks, @willarmiros, I am sure you are already aware of this but still going to say it: more frequent releases would be greatly appreciated 🙏 

Looking forward to the next one! 👋 

<img width="418" alt="Screenshot 2023-03-28 at 18 27 50" src="https://user-images.githubusercontent.com/1692632/228306827-17c8171b-7b5a-4edd-b06d-4695dd8fec86.png">
